services:

  postgres:
    image: postgres:16
    container_name: skillgap-postgres

    environment:
      POSTGRES_DB: skillgap
      POSTGRES_USER: skillgap_user
      POSTGRES_PASSWORD: skillgap_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: